CREATE TABLE PELANGGAN
(
	Id_Pelanggan CHAR (5) NOT NULL,
	Nama_Pelanggan VARCHAR (50) NOT NULL,
	Alamat_Pelanggan VARCHAR (50) NOT NULL,
	Id_Kecamatan CHAR (5) NOT NULL,
	Id_Kelurahan CHAR (5) NOT NULL,
	Tempat_lahir VARCHAR (50) NOT NULL,
	Tgl_lahir DATE NOT NULL,
	No_rekening VARCHAR (15) NOT NULL,
	No_telp VARCHAR (15) NOT NULL,
	Jenis_kelamin VARCHAR (10) NOT NULL,
	Pekerjaan VARCHAR (20) NOT NULL,
	Email VARCHAR (50) NOT NULL,
	Pass VARCHAR (50) NOT NULL,
	Keterangan VARCHAR (10),
	PRIMARY KEY (Id_Pelanggan),
	FOREIGN KEY (Id_Kecamatan) REFERENCES KECAMATAN (Id_Kecamatan) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Id_Kelurahan) REFERENCES KELURAHAN (Id_Kelurahan)ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT IPN CHECK (Id_Pelanggan LIKE 'IP[0-9][0-9][0-9]'),
	CONSTRAINT PelGen CHECK (Jenis_kelamin IN ('Male','Female'))
);

CREATE TABLE KECAMATAN
(
	Id_Kecamatan CHAR (5) NOT NULL,
	Nama_Kecamatan VARCHAR (50) NOT NULL,
	PRIMARY KEY (Id_Kecamatan),
	CONSTRAINT IKC CHECK (Id_Kecamatan LIKE 'IC[0-9][0-9][0-9]')
);

CREATE TABLE KELURAHAN
(
	Id_Kelurahan CHAR (5) NOT NULL,
	Nama_Kelurahan VARCHAR (50) NOT NULL,
	PRIMARY KEY (Id_Kelurahan),
	CONSTRAINT IKL CHECK (Id_Kelurahan LIKE 'IL[0-9][0-9][0-9]')
);

CREATE TABLE KARYAWAN
(
	Id_Karyawan CHAR (5) NOT NULL,
	Nama_Karyawan VARCHAR (50) NOT NULL,
	Alamat_Karyawan VARCHAR (50) NOT NULL,
	No_telp VARCHAR (15) NOT NULL,
	Jenis_kelamin VARCHAR (10) NOT NULL,
	Email VARCHAR (50) NOT NULL,
	Pass VARCHAR (50) NOT NULL,
	PRIMARY KEY (Id_Karyawan),
	CONSTRAINT IKN CHECK (Id_Karyawan LIKE 'IK[0-9][0-9][0-9]'),
	CONSTRAINT KarGen CHECK(Jenis_kelamin IN ('Male','Female'))
);

CREATE TABLE PICKUP
(
	Id_Pelanggan CHAR (5) NOT NULL,
	Id_Sampah CHAR (5) NOT NULL,
	Id_Karyawan CHAR (5) NOT NULL,
	Id_Pickup CHAR (5) NOT NULL,
	PRIMARY KEY (Id_Pickup),
	FOREIGN KEY (Id_Pelanggan) REFERENCES PELANGGAN (Id_Pelanggan),
	FOREIGN KEY (Id_Sampah) REFERENCES SAMPAH (Id_Sampah) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Id_Karyawan) REFERENCES KARYAWAN (Id_Karyawan) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT IPC CHECK (Id_Pickup LIKE 'IU[0-9][0-9][0-9]'),
);

CREATE TABLE Detail_Pickup
(
	Id_Pickup CHAR (5) NOT NULL,
	Tgl_Pickup DATE NOT NULL,
	Total_Berat VARCHAR (10) NOT NULL,
	Waktu TIME NOT NULL,
	PRIMARY KEY (Id_Pickup),
	FOREIGN KEY (Id_Pickup) REFERENCES PICKUP (Id_Pickup)ON UPDATE CASCADE ON DELETE CASCADE,
);

CREATE TABLE SAMPAH
(
	Id_Sampah CHAR (5) NOT NULL,
	Jenis_Sampah VARCHAR (10) NOT NULL,
	Harga_Sampah NUMERIC (11,2) NOT NULL,
	PRIMARY KEY (Id_Sampah),
	CONSTRAINT ISP CHECK (Id_Sampah LIKE 'IS[0-9][0-9][0-9]'),
	CONSTRAINT JS CHECK (Jenis_Sampah IN ('Organik','Anorganik','Berbahaya'))
);
CREATE TABLE PENGEPUL
(
	Id_Pengepul CHAR (5) NOT NULL,
	Id_Sampah CHAR (5) NOT NULL,
	Alamat_Pengepul VARCHAR (50) NOT NULL,
	Id_Karyawan CHAR (5) NOT NULL,
	PRIMARY KEY (Id_Pengepul),
	FOREIGN KEY (Id_Sampah) REFERENCES SAMPAH (Id_Sampah)ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Id_Karyawan) REFERENCES KARYAWAN (Id_Karyawan)ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT PGP CHECK (Id_Pengepul LIKE 'PG[0-9][0-9][0-9]'),
);
CREATE TABLE PEMILAH
(
	Id_Pemilah CHAR (5) NOT NULL,
	Id_Karyawan CHAR (5) NOT NULL,
	Id_Sampah CHAR (5) NOT NULL,
	Biaya_Pemilah NUMERIC (11,2) NOT NULL,
	Berat_Sampah VARCHAR (10) NOT NULL,
	PRIMARY KEY (Id_Pemilah),
	FOREIGN KEY (Id_Karyawan) REFERENCES KARYAWAN (Id_Karyawan)ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Id_Sampah) REFERENCES SAMPAH (Id_Sampah) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT PML CHECK (Id_Pemilah LIKE 'PM[0-9][0-9][0-9]'),
);
CREATE TABLE PENGOLAH_SAMPAH
(
	Id_Pengolah CHAR (5) NOT NULL,
	Id_Karyawan CHAR(5) NOT NULL,
	Id_Sampah CHAR (5) NOT NULL,
	Biaya_Pemilah NUMERIC (11,2) NOT NULL,
	Berat_Sampah VARCHAR (10) NOT NULL,
	PRIMARY KEY (Id_Pengolah),
	FOREIGN KEY (Id_Karyawan) REFERENCES KARYAWAN (Id_Karyawan)ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (Id_Sampah) REFERENCES SAMPAH (Id_Sampah)ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT PGS CHECK (Id_Pengolah LIKE 'PS[0-9][0-9][0-9]'),
);
CREATE TABLE TRANSAKSI
(
	Id_Transaksi CHAR (5) NOT NULL,
	Id_Pickup CHAR (5) NOT NULL,
	Total_Harga NUMERIC (11,2) NOT NULL,
	PRIMARY KEY (Id_Transaksi),
	FOREIGN KEY (Id_Pickup) REFERENCES PICKUP (Id_Pickup) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT TSK CHECK (Id_Transaksi LIKE 'TS[0-9][0-9][0-9]')
);
CREATE TABLE DETAIL_TRANSAKSI
(
	Id_Transaksi CHAR (5) NOT NULL,
	Tgl_Transaksi DATE NOT NULL,
	PaymentType VARCHAR (20) NOT NULL, 
	PRIMARY KEY (Id_Transaksi),
	FOREIGN KEY (Id_Transaksi) REFERENCES TRANSAKSI (Id_Transaksi) ON UPDATE CASCADE ON DELETE CASCADE,
);